/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion.forms;

import java.awt.Dimension;



/**
 *
 * @authores : Eli y Dina
 */
public class ZMenu extends javax.swing.JInternalFrame {

    /**
     * Creates new form ZMenu
     */
//        JDesktopPane theDesktop = new JDesktopPane();
//------------------------------------------------------
    public ZMenu() {
        initComponents();
//        getContentPane().add( theDesktop);
//        theDesktop.setBackground(Color.blue);
//      
     this.setSize(new Dimension(550, 360));
//          this.setContentPane(theDesktop);
    }
//------------------------------------------------------
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooserMenu = new javax.swing.JFileChooser();

        jFileChooserMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFileChooserMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jFileChooserMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jFileChooserMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jFileChooserMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFileChooserMenuActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_jFileChooserMenuActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser jFileChooserMenu;
    // End of variables declaration//GEN-END:variables
}
